### ISSUE TITLE
During cleaning proceee i reciver: propably reason is polish language char.

### ISSUE THREAD

**Issue by budwig** [ehaupt/cleanup-maildir#1]
INFO:MaildirCleaner:Archiving #7 to Archive.2017: FW: 17095 ETHERNET
Traceback (most recent call last):
  File "/data/vmail/cleanup-maildir", line 528, in <module>
    cleaner.clean(mode, dir, minAge)
  File "/data/vmail/cleanup-maildir", line 425, in clean
    self.__mdWriter.deliver(msg, sfPath)
  File "/data/vmail/cleanup-maildir", line 153, in deliver
    self.logger.INFO("deliver: attempt copy %s to %s" %
AttributeError: Logger instance has no attribute 'INFO'

Is any possibility to resolve this?

**Comment by ehaupt** [comment]
What python version are you using?

```
python3 -V
```
